version: '3.3'
services: 
    web: 
        build: 
            context: .
            dockerfile: Dockerfile
        image: phuocvinh143/php:7.4.3-apache
        container_name: php74
        depends_on: 
            - db
        volumes: 
            - ../:/var/www/html/
        ports:
            - 8000:80
    db: 
        container_name: mysql80
        image: phuocvinh143/php:8.0-mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ../myblog.sql:/docker-entrypoint-initdb.d/myblog.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myblog
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports: 
            - 6033:3306
